apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-produto
  template:
    metadata:
      labels:
        app: api-produto
    spec:
      containers:
        - name: api-produto
          image: lgro1991/api-produto:latest
          ports:
            - containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /read
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # resources:
          #   requests:
          #     cpu: "200m"
          #     memory: "32Mi"
          #   limits:
          #     cpu: "400m"
          #     memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: api-produto
spec:
  selector:
    app: api-produto
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: api-produto
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60